### ISSUE TITLE
Run StataPush in presence of errors.

### ISSUE THREAD

**Issue by vikjam** [wschpero/statapush#1]
Hi! 

I [forked your project](https://github.com/vikjam/statapush), adding the option to run a do file and get a notification even if the do-file errors out. For example,

``` stata
* Install fork
net install statapush, from("https://raw.github.com/vikjam/statapush/master/") replace

* Create an example do file that has an error
file open example using "example-do.do", write
file write example "sysuse auto.dta" _n "regressx mpg price" _n
file close example

* Run statapush
statapush using "example-do.do", token(<INSERT API TOKEN>) userid(<INSERT USER KEY>) message(<INSERT MESSAGE>)
```

You should see the following notification,

![example](https://cloud.githubusercontent.com/assets/1154799/13013121/15915934-d17c-11e5-9d0a-4c8ecb71b7d5.png)

Basically, I'm basically just using the `do` command in Stata with error handling.

If you think it's useful, I can submit a pull request and edit the help file accordingly. If not, no worries!

By the way, I have a [similar thing](https://github.com/vikjam/teller) going for qsub (using Pushbullet for the notifications). It's still very much a work in progress though!

**Comment by wschpero** [comment]
Hi!

Thanks for the contribution - this was very much on my list. Let me take a look this weekend and get back to you.

Best,
Will
