### ISSUE TITLE
Problems with Windows and PushBullet

### ISSUE THREAD

**Issue by DrLeoSpaceman** [wschpero/statapush#5]
Hi,
First, thanks for writing this module. Definitely very helpful.

Just wanted to point out one issue that is only a problem when using Windows and Pushbullet. When the module sends the curl command, it fails since the windows shell does not correctly parse the command as written. This is due to the fact that the Windows command line does not understand single quotes. I was able to get it working by modifying the ado file so that the relevant command (line 64) is:

`quietly !curl -u "`token'": -X POST https://api.pushbullet.com/v2/pushes --header "Content-Type: application/json" --data-binary "{\"type\": \"note\", \"title\": \"statapush\", \"body\": \"`message'\"}"`

**Comment by wschpero** [comment]
Hi,

Thanks so much for the heads up. We're hoping to add some new features to the module in the next week or so, and I'll make sure this bug is addressed in that release.

Best,
Will

**Comment by wschpero** [comment]
Should be fixed now on Github! Will submit a revised version to SSC soon. Thx!
