### ISSUE TITLE
cURL installation

### ISSUE THREAD

**Issue by flozanor82** [wschpero/statapush#7]
Hi,

It would be very helpful to get an exampl of the installation of cURL for Windows. I have found some but they require the use of a different than Pushbullet platform. ?Do you know of any example?
Thanks in advance.
Cheers,
Felipe

**Comment by wschpero** [comment]
Hi Felipe,

I unfortunately don't have access to a Windows machine at the moment and thus can't provide much guidance about cURL installation on that OS beyond what's available via Google. That being said, I should note that statapush is designed to work with a number of different push notification platforms, including Pushover and IFTTT. If you're having trouble getting Pushbullet to work, perhaps it's worth trying a different provider?

Hope this helps!

Best,
Will
